Automated commit: Mon Aug 19 02:57:33 +07 2024

diff --git a/.github/workflows/service-ci.yaml b/.github/workflows/service-ci.yaml
--- a/.github/workflows/service-ci.yaml
+++ b/.github/workflows/service-ci.yaml
@@ -15,6 +15,7 @@ on:
 env:
   GO_VERSION: '1.20'
   HELM_VERSION: 'v3.13.3'
+  HELM_FOLDER: ./app
 
 jobs:
   unit-tests:
@@ -68,7 +69,7 @@ jobs:
 
     - name: Lint Helm Chart
       run: |
-        helm lint ./app
+        helm lint ${{ env.HELM_FOLDER }}
 
   containerize:
     runs-on: ubuntu-latest
@@ -99,3 +100,33 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
+
+    - name: Package Chart
+      run: |
+        helm package ${{ env.HELM_FOLDER }} --destination charts
+        helm repo index charts --url ${{ vars.HELM_REPO_URL }}
+
+    - name: Commit and push
+      working-directory: debt-tracker
+      run: |
+        git config user.name "${GITHUB_ACTOR}"
+        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+
+        if [[ $(git status --porcelain) ]]; then
+          if ! git add .; then
+            echo "Error: Failed to stage files"
+          fi
+
+          if ! git commit -m "Updated from ref: ${{ github.sha }}"; then
+            echo "Error: Failed to commit files"
+          fi
+
+          if ! git push; then
+            if ! git pull --rebase && git push; then
+              echo "Error: failed to push the code."
+              exit 1
+            fi
+          fi
+        else
+          echo "Nothing to commit."
+        fi
